id: A38304057
title: Averting Obstacles through Sitātapatrā
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:37:15.389182
  last_modified_at: 2022-03-01 00:37:15.389192
